[28/Nov/2020:23:39:12] ENGINE Listening for SIGUSR1.
[28/Nov/2020:23:39:12] ENGINE Listening for SIGTERM.
[28/Nov/2020:23:39:12] ENGINE Listening for SIGHUP.
[28/Nov/2020:23:39:12] ENGINE Bus STARTING
[28/Nov/2020:23:39:12] ENGINE Serving on http://0.0.0.0
[28/Nov/2020:23:39:12] ENGINE Bus STARTED
[28/Nov/2020:23:39:28] HTTP 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "server.py", line 20, in check
    return str(html_template)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
  File "_Users_Home_Development_fakedestroyer_templates_check_html.py", line 124, in respond
NameMapper.NotFound: cannot find 'document'
[29/Nov/2020:00:02:09] ENGINE Keyboard Interrupt: shutting down bus
[29/Nov/2020:00:02:09] ENGINE Bus STOPPING
[29/Nov/2020:00:02:09] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 80)) shut down
[29/Nov/2020:00:02:09] ENGINE Bus STOPPED
[29/Nov/2020:00:02:09] ENGINE Bus EXITING
[29/Nov/2020:00:02:09] ENGINE Bus EXITED
[29/Nov/2020:00:02:09] ENGINE Waiting for child threads to terminate...
[29/Nov/2020:00:02:09] ENGINE Waiting for thread HTTPServer Thread-1.
[29/Nov/2020:00:06:31] ENGINE Listening for SIGHUP.
[29/Nov/2020:00:06:31] ENGINE Listening for SIGUSR1.
[29/Nov/2020:00:06:31] ENGINE Listening for SIGTERM.
[29/Nov/2020:00:06:31] ENGINE Bus STARTING
[29/Nov/2020:00:06:31] ENGINE Serving on http://0.0.0.0
[29/Nov/2020:00:06:31] ENGINE Bus STARTED
[29/Nov/2020:00:41:13] ENGINE Keyboard Interrupt: shutting down bus
[29/Nov/2020:00:41:13] ENGINE Bus STOPPING
[29/Nov/2020:00:41:13] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 80)) shut down
[29/Nov/2020:00:41:13] ENGINE Bus STOPPED
[29/Nov/2020:00:41:13] ENGINE Bus EXITING
[29/Nov/2020:00:41:13] ENGINE Bus EXITED
[29/Nov/2020:00:41:13] ENGINE Waiting for child threads to terminate...
[29/Nov/2020:00:41:15] ENGINE Listening for SIGTERM.
[29/Nov/2020:00:41:15] ENGINE Listening for SIGHUP.
[29/Nov/2020:00:41:15] ENGINE Listening for SIGUSR1.
[29/Nov/2020:00:41:15] ENGINE Bus STARTING
[29/Nov/2020:00:41:15] ENGINE Serving on http://0.0.0.0
[29/Nov/2020:00:41:15] ENGINE Bus STARTED
[29/Nov/2020:00:41:23] HTTP 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "server.py", line 39, in api
    response = generate_response()
TypeError: generate_response() missing 1 required positional argument: 'data'
[29/Nov/2020:00:41:38] ENGINE Keyboard Interrupt: shutting down bus
[29/Nov/2020:00:41:38] ENGINE Bus STOPPING
[29/Nov/2020:00:41:38] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 80)) shut down
[29/Nov/2020:00:41:38] ENGINE Bus STOPPED
[29/Nov/2020:00:41:38] ENGINE Bus EXITING
[29/Nov/2020:00:41:38] ENGINE Bus EXITED
[29/Nov/2020:00:41:38] ENGINE Waiting for child threads to terminate...
[29/Nov/2020:00:41:39] ENGINE Listening for SIGHUP.
[29/Nov/2020:00:41:39] ENGINE Listening for SIGTERM.
[29/Nov/2020:00:41:39] ENGINE Listening for SIGUSR1.
[29/Nov/2020:00:41:39] ENGINE Bus STARTING
[29/Nov/2020:00:41:39] ENGINE Serving on http://0.0.0.0
[29/Nov/2020:00:41:39] ENGINE Bus STARTED
[29/Nov/2020:01:16:56] ENGINE Keyboard Interrupt: shutting down bus
[29/Nov/2020:01:16:56] ENGINE Bus STOPPING
[29/Nov/2020:01:16:56] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 80)) shut down
[29/Nov/2020:01:16:56] ENGINE Bus STOPPED
[29/Nov/2020:01:16:56] ENGINE Bus EXITING
[29/Nov/2020:01:16:56] ENGINE Bus EXITED
[29/Nov/2020:01:16:56] ENGINE Waiting for child threads to terminate...
[29/Nov/2020:01:16:58] ENGINE Listening for SIGUSR1.
[29/Nov/2020:01:16:58] ENGINE Listening for SIGTERM.
[29/Nov/2020:01:16:58] ENGINE Listening for SIGHUP.
[29/Nov/2020:01:16:58] ENGINE Bus STARTING
[29/Nov/2020:01:16:59] ENGINE Serving on http://0.0.0.0
[29/Nov/2020:01:16:59] ENGINE Bus STARTED
[29/Nov/2020:01:17:07] HTTP 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "server.py", line 64, in api
    response = generate_response(data)
  File "server.py", line 30, in generate_response
    result = fetch_items(data)
  File "server.py", line 13, in fetch_items
    connection = mysql.connector.connect(host="127.0.0.1", user="root", passwd="root", db="fakedestroyer", charset='utf8')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/__init__.py", line 179, in connect
    return MySQLConnection(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/abstracts.py", line 716, in connect
    self._open_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/connection.py", line 210, in _open_connection
    self._ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/connection.py", line 142, in _do_auth
    auth_plugin=self._auth_plugin)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/protocol.py", line 102, in make_auth
    auth_data, ssl_enabled)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/protocol.py", line 58, in _auth_response
    auth = get_auth_plugin(auth_plugin)(
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/authentication.py", line 191, in get_auth_plugin
    "Authentication plugin '{0}' is not supported".format(plugin_name))
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported
[29/Nov/2020:01:21:58] HTTP 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "server.py", line 64, in api
    response = generate_response(data)
  File "server.py", line 30, in generate_response
    result = fetch_items(data)
  File "server.py", line 13, in fetch_items
    connection = mysql.connector.connect(host="127.0.0.1", user="root", passwd="root", db="fakedestroyer", charset='utf8')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/__init__.py", line 179, in connect
    return MySQLConnection(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/abstracts.py", line 716, in connect
    self._open_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/connection.py", line 210, in _open_connection
    self._ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/connection.py", line 142, in _do_auth
    auth_plugin=self._auth_plugin)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/protocol.py", line 102, in make_auth
    auth_data, ssl_enabled)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/protocol.py", line 58, in _auth_response
    auth = get_auth_plugin(auth_plugin)(
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/authentication.py", line 191, in get_auth_plugin
    "Authentication plugin '{0}' is not supported".format(plugin_name))
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported
[29/Nov/2020:01:23:17] HTTP 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "server.py", line 64, in api
    response = generate_response(data)
  File "server.py", line 30, in generate_response
    result = fetch_items(data)
  File "server.py", line 13, in fetch_items
    connection = mysql.connector.connect(host="127.0.0.1", user="root", passwd="root", db="fakedestroyer", charset='utf8')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/__init__.py", line 179, in connect
    return MySQLConnection(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/abstracts.py", line 716, in connect
    self._open_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/connection.py", line 210, in _open_connection
    self._ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/connection.py", line 142, in _do_auth
    auth_plugin=self._auth_plugin)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/protocol.py", line 102, in make_auth
    auth_data, ssl_enabled)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/protocol.py", line 58, in _auth_response
    auth = get_auth_plugin(auth_plugin)(
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mysql/connector/authentication.py", line 191, in get_auth_plugin
    "Authentication plugin '{0}' is not supported".format(plugin_name))
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported
[29/Nov/2020:01:38:09] ENGINE Keyboard Interrupt: shutting down bus
[29/Nov/2020:01:38:09] ENGINE Bus STOPPING
[29/Nov/2020:01:38:09] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 80)) shut down
[29/Nov/2020:01:38:09] ENGINE Bus STOPPED
[29/Nov/2020:01:38:09] ENGINE Bus EXITING
[29/Nov/2020:01:38:09] ENGINE Bus EXITED
[29/Nov/2020:01:38:09] ENGINE Waiting for child threads to terminate...
